### ISSUE TITLE
LUIS cannot take care of special characters.

### ISSUE THREAD

**Issue by Wedeo95** [Microsoft/Cognitive-LUIS-Windows#54]
![image](https://user-images.githubusercontent.com/30614421/28904295-e821a672-785d-11e7-959f-4ca1a8b6381b.png)

**Comment by stevengum97** [comment]
@Wedeo95, can you explain which special characters you're using?

**Comment by tellarin** [comment]
Hi @Wedeo95, can you please provide more details?

**Comment by hpascaud** [comment]
Hi, I don't know if @Wedeo95 is talking about entities but it seems that LUIS is not able to understand that a word, with a special character like "-", must be seen completely as the content of an entity.
Only the first part of the word is understood by LUIS as the content of the entity.

I cannot see how to tell it to accept this kind of particularity, knowing that I can't use phrase lists as I want the user to tell me some information I may not know (for example, the name of a very small town that nobody knows).

**Comment by hpascaud** [comment]
I am sorry, finally that works but it took me some time to understand. 
The way to do is not so instinctive.
With the LUIS interface, it is possible to make understand to an utterance the character "-" by selecting the first part of the word, then selecting the "-" and at last the final part. After that, you are able to say which entity it is relative to.
You must not try to select the whole word with only one click because that way does not works.

Though, there is one important detail but it may be now a problem with my code :
It seems that LUIS send back the content of the entity with spaces between the "-".
Example: you enter "first-last" and LUIS seems to send back "first - last"

Does any one has the same result ?

**Comment by sunilsoniudaipur** [comment]
how we can ignore punctuation marks from the utterances like (? . , !) as they impact on the predictions. is there any way form which we can configure Luis to ignore punctuation marks.

**Comment by omaremadeldin** [comment]
@sunilsoniudaipur You can use utterance normalization which documented over here: https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-concept-utterance#utterance-normalization
